name: publish to nuget
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v2.4.2
    # Setting Up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    # Build
    - name: Build
      run: dotnet build --configuration Release
    # Test
    - name: Test
      run: dotnet test
    # Publish
    - name: Pack
      run: dotnet pack src\CodePant.DotNet.Helper\CodePant.DotNet.Helper.csproj -o out -c Release -o out
    - name: Push 
      run: dotnet nuget push out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
    - name: Success Log
      run: |
        echo Package Successfully Published To Nuget.
